name: Build, Test, and Deploy to EC2 using Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t devops_project .

    - name: Save Docker image as tar
      run: docker save devops_project -o devops_project.tar

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "devops_project.tar"
        target: "~/devops_project/"

    - name: Load and run container on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/devops_project
          docker load -i devops_project.tar
          docker stop devops_project || true
          docker rm devops_project || true
          docker run -d --name devops_project -p 80:3000 devops_project
